/* Only for QMP V5 PHY - UFS PCS registers */
/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2017, The Linux Foundation. All rights reserved.
 */

#ifndef QCOM_PHY_QMP_PCS_UFS_V5_H_
#define QCOM_PHY_QMP_PCS_UFS_V5_H_

/* Only for QMP V5 PHY - UFS PCS registers */
#define QPHY_V5_PCS_UFS_PHY_START			0x000
#define QPHY_V5_PCS_UFS_POWER_DOWN_CONTROL		0x004
#define QPHY_V5_PCS_UFS_SW_RESET			0x008
#define QPHY_V5_PCS_UFS_TIMER_20US_CORECLK_STEPS_MSB	0x00c
#define QPHY_V5_PCS_UFS_TIMER_20US_CORECLK_STEPS_LSB	0x010
#define QPHY_V5_PCS_UFS_LINE_RESET_TIME			0x014
#define QPHY_V5_PCS_UFS_LINE_RESET_GRANULARITY		0x018
#define QPHY_V5_PCS_UFS_TSYNC_RSYNC_CNTL		0x024
#define QPHY_V5_PCS_UFS_PLL_CNTL			0x02c
#define QPHY_V5_PCS_UFS_TX_LARGE_AMP_DRV_LVL		0x030
#define QPHY_V5_PCS_UFS_TX_LARGE_AMP_POST_EMP_LVL	0x034
#define QPHY_V5_PCS_UFS_TX_SMALL_AMP_DRV_LVL		0x038
#define QPHY_V5_PCS_UFS_TX_SMALL_AMP_POST_EMP_LVL	0x03c
#define QPHY_V5_PCS_UFS_CFG_CHANGE_CNT_VAL		0x040
#define QPHY_V5_PCS_UFS_RX_SYNC_WAIT_TIME		0x048
#define QPHY_V5_PCS_UFS_BIST_FIXED_PAT_CTRL		0x060
#define QPHY_V5_PCS_UFS_TX_HSGEAR_CAPABILITY		0x074
#define QPHY_V5_PCS_UFS_TX_PWMGEAR_CAPABILITY		0x078
#define QPHY_V5_PCS_UFS_RX_HSGEAR_CAPABILITY		0x0b4
#define QPHY_V5_PCS_UFS_RX_PWMGEAR_CAPABILITY		0x0b8
#define QPHY_V5_PCS_UFS_RX_MIN_SLEEP_NOCONFIG_TIME_CAPABILITY	0x0c4
#define QPHY_V5_PCS_UFS_RX_MIN_STALL_NOCONFIG_TIME_CAPABILITY	0x0c8
#define QPHY_V5_PCS_UFS_RX_MIN_SAVE_CONFIG_TIME_CAPABILITY	0x0cc
#define QPHY_V5_PCS_UFS_RX_HS_G1_SYNC_LENGTH_CAPABILITY	0x0d4
#define QPHY_V5_PCS_UFS_RX_LS_PREPARE_LENGTH_CAPABILITY	0x0dc
#define QPHY_V5_PCS_UFS_RX_PWM_BURST_CLOSURE_LENGTH_CAPABILITY	0x0e0
#define QPHY_V5_PCS_UFS_RX_MIN_ACTIVATETIME_CAPABILITY	0x0e4
#define QPHY_V5_PCS_UFS_DEBUG_BUS_CLKSEL		0x124
#define QPHY_V5_PCS_UFS_LINECFG_DISABLE			0x148
#define QPHY_V5_PCS_UFS_RX_SYM_RESYNC_CTRL		0x14c
#define QPHY_V5_PCS_UFS_RX_MIN_HIBERN8_TIME		0x150
#define QPHY_V5_PCS_UFS_RX_SIGDET_CTRL1			0x154
#define QPHY_V5_PCS_UFS_RX_SIGDET_CTRL2			0x158
#define QPHY_V5_PCS_UFS_TX_PWM_GEAR_BAND		0x160
#define QPHY_V5_PCS_UFS_RX_PWM_GEAR_BAND		0x164
#define QPHY_V5_PCS_UFS_TX_HS_GEAR_BAND			0x168
#define QPHY_V5_PCS_UFS_READY_STATUS			0x180
#define QPHY_V5_PCS_UFS_LINECFG_HIGHZ_COUNT_CTRL	0x1b4
#define QPHY_V5_PCS_UFS_LINECFG_HIGHZ_COUNT_INIT_G1	0x1b8
#define QPHY_V5_PCS_UFS_LINECFG_HIGHZ_COUNT_INIT_G3	0x1c0
#define QPHY_V5_PCS_UFS_LINECFG_HIGHZ_COUNT_INIT_G4	0x1c4
#define QPHY_V5_PCS_UFS_TX_MID_TERM_CTRL1		0x1d8
#define QPHY_V5_PCS_UFS_MULTI_LANE_CTRL1		0x1e0

#endif
